import { Bell, ChevronDown, Command, LayoutDashboard, Moon, Search, Settings, ShieldAlert, Sliders, Sparkles, Sun, Target, UploadCloud, Users, WalletCards } from "lucide-react";
import { useState } from "react";
import { NavLink, Outlet } from "react-router-dom";
import { AiChatDrawer } from "../chat/AiChatDrawer";

const navGroups = [
  { label: "Workspace", items: [{ to: "/dashboard", label: "Overview", icon: LayoutDashboard }, { to: "/customers", label: "Customers", icon: Users }, { to: "/churn", label: "Churn analytics", icon: ShieldAlert }, { to: "/segments", label: "Segments", icon: Target }] },
  { label: "Analysis", items: [{ to: "/cohorts", label: "Cohorts", icon: Command }, { to: "/revenue-risk", label: "Revenue at risk", icon: WalletCards }, { to: "/retention", label: "Action center", icon: Sparkles }, { to: "/simulator", label: "What-If Simulator", icon: Sliders }, { to: "/model", label: "Model performance", icon: Settings }] },
];

export function AppLayout() {
  const [dark, setDark] = useState(false);
  return <div className={dark ? "app-frame dark-mode" : "app-frame"}><aside className="sidebar"><div className="brand"><span>CI</span><div><strong>CustomerIQ</strong><small>Intelligence platform</small></div></div><div className="workspace-switch"><span className="workspace-avatar">CI</span><div><b>CustomerIQ Platform</b><small>Live Analytics</small></div><ChevronDown size={14} /></div><nav>{navGroups.map((group) => <div className="nav-group" key={group.label}><small className="nav-label">{group.label}</small>{group.items.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => isActive ? "nav-link active" : "nav-link"}><Icon size={17} />{label}</NavLink>)}</div>)}<div className="nav-group"><small className="nav-label">Data</small><NavLink to="/upload" className={({ isActive }) => isActive ? "nav-link active" : "nav-link"}><UploadCloud size={17} />Upload data</NavLink></div></nav><div className="sidebar-bottom"><div className="usage"><span>Data freshness</span><strong>Live connected</strong><div><i /></div></div><NavLink to="/settings" className="nav-link"><Settings size={17} />Settings</NavLink><div className="user-row"><span className="avatar">SO</span><div><b>Soham</b><small>Administrator</small></div><ChevronDown size={14} /></div></div></aside><main className="main-area"><header className="top-nav"><div className="mobile-brand">CustomerIQ</div><div className="global-search"><Search size={16} /><input placeholder="Search anything..." /><kbd>⌘ K</kbd></div><div className="top-actions"><span className="demo-pill" style={{ background: "rgba(16, 185, 129, 0.12)", color: "#059669" }}><i style={{ background: "#10b981" }} /> Live API Connected</span><button aria-label="Toggle theme" onClick={() => setDark((value) => !value)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button aria-label="Notifications"><Bell size={17} /><i className="notification-dot" /></button><span className="top-avatar">SO</span></div></header><div className="page-content"><Outlet /></div><AiChatDrawer /></main></div>;
}
